# fly.toml app configuration file generated for fibonacci-easy-vote on 2025-06-04T02:00:34Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'fibonacci-easy-vote'
primary_region = 'sjc'

[build]

[http_service]
auto_start_machines = true
auto_stop_machines = 'off'
force_https = true
internal_port = 3000
min_machines_running = 0
processes = ['app']

[[vm]]
cpu_kind = 'shared'
cpus = 1
memory = '1gb'
memory_mb = 1024

[processes]
app = 'npm run start'
